fiapx-user-management:
  replicaCount: 2

  image:
    repository: loadinggreg/fiapx-user-management
    tag: latest
    pullPolicy: IfNotPresent

  service:
    type: LoadBalancer
    port: 80
    targetPort: 8080
    nodePort: 30080

  mysql:
    database: springdb
    user: springuser

fiapx-video-processor:
  replicaCount: 2

  storage:
    type: aws
    uploadDir: fiapx-uploaded-videos-0
    ouputDir: fiapx-resulted-zipfiles-0
    aws:
      credentials: session
      region: us-east-1

  image:
    repository: loadinggreg/fiapx-video-processor
    tag: latest
    pullPolicy: IfNotPresent

  service:
    type: LoadBalancer
    port: 80
    targetPort: 8080
    nodePort: 30081

  mysql:
    database: springdb
    user: springuser

  persistence:
    size: 
    storageClass: 