fiapx-user-management:
  replicaCount: 2

  image:
    repository: loadinggreg/fiapx-user-management
    tag: latest
    pullPolicy: Always

  service:
    type: NodePort
    port: 80
    targetPort: 8080
    nodePort: 30080

  mysql:
    database: springdb
    user: springuser
    host: localhost
    port: 3306

fiapx-video-processor:
  replicaCount: 2

  image:
    repository: loadinggreg/fiapx-video-processor
    tag: latest
    pullPolicy: Always

  service:
    type: NodePort
    port: 80
    targetPort: 8080
    nodePort: 30081

  storage:
    type: local
    uploadDir: uploads
    outputDir: output
    aws:
      credentials: session
      region: aws-region

  mysql:
    database: springdb
    user: springuser
    host: localhost
    port: 3306

  persistence:
    size: 10Gi
    storageClass: standard

  userManagement:
    url: "http://fiapx-user-management-cluster-ip-svc:80"