fiapx-user-management:
  replicaCount: 2

  image:
    repository: loadinggreg/fiapx-user-management
    tag: latest
    pullPolicy: Always

  service:
    type: LoadBalancer
    port: 80
    targetPort: 8080
    nodePort: 30080

  mysql:
    database: user_management_db
    user: springuser
    host: localhost
    port: 3306

fiapx-video-processor:
  replicaCount: 2

  storage:
    type: aws
    uploadDir: fiapx-uploaded-videos-d27d8e32-c0bd-4f5c-8b97-dd1310b3a289
    outputDir: fiapx-resulted-zipfiles-d27d8e32-c0bd-4f5c-8b97-dd1310b3a289
    aws:
      credentials: session
      region: us-east-1

  image:
    repository: loadinggreg/fiapx-video-processor
    tag: latest
    pullPolicy: Always

  service:
    type: LoadBalancer
    port: 80
    targetPort: 8080
    nodePort: 30081

  mysql:
    database: video_processor_db
    user: springuser
    host: localhost
    port: 3306

  persistence:
    size: 
    storageClass: 

  userManagement:
    url: "http://fiapx-user-management-cluster-ip-svc:80"