name: Run Postman Tests with Newman

on:
  repository_dispatch:
    types: [trigger-newman-tests]

jobs:
  newman-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: us-east-1

      - name: Install Newman
        run: npm install -g newman

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v2
        with:
            terraform_wrapper: false

      - name: Terraform init
        working-directory: ./terraform/integration
        run: 
            terraform init

      - name: Capture API Gateway Endpoint
        working-directory: ./terraform/integration
        run: |
            echo "USER_MANAGEMENT=$(terraform output -raw user_management_api_gateway_url)" >> $GITHUB_ENV
            echo "VIDEO_PROCESSOR=$(terraform output -raw video_processor_api_gateway_url)" >> $GITHUB_ENV

      - name: Run Collection
        run: |
          newman run tests/postman/fiapx.postman_collection.json \
            -e tests/postman/EKS.postman_environment.json \
            --env-var "USER_MANAGEMENT=${{ env.USER_MANAGEMENT }}"
            --env-var "VIDEO_PROCESSOR=${{ env.VIDEO_PROCESSOR }}"
            --reporters cli,json \
            --reporter-json-export results.json

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
            name: results
            path: results.json
