name: Terraform Cluster Deploy

on:
  workflow_run:
    workflows: ["Deploy Helm Chart to EKS"]
    types:
      - completed

jobs:
  service-dns:
    runs-on: ubuntu-latest
    outputs:
      nlb_dns: ${{ steps.get_nlb.outputs.nlb_dns }}
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Update kubeconfig
        run: |
          aws eks update-kubeconfig --region ${{ secrets.AWS_REGION }} --name academy-eks-cluster

      - name: Install kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'latest'

      - name: Get NLB DNS and write to file
        id: get_nlb
        run: |
          NLB_DNS=$(kubectl get svc fiapx-user-management-svc -n default -o jsonpath='{.status.loadBalancer.ingress[0].hostname}')
          echo $NLB_DNS
          ENCODED_NLB_DNS=$(echo -n "${NLB_DNS}" | base64)
          echo "nlb_dns=${ENCODED_NLB_DNS}" >> "$GITHUB_OUTPUT"

  terraform:
    runs-on: ubuntu-latest
    needs: service-dns

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: us-east-1

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform Init
        working-directory: ./terraform/integration
        run: |
          export TF_LOG=DEBUG
          terraform init

      - name: Terraform Apply
        working-directory: ./terraform/integration
        run: |
          NLB_DNS=$(echo "${{ needs.service-dns.outputs.nlb_dns }}" | base64 --decode)
          terraform apply -auto-approve \
          -var "aws_region=us-east-1" \
          -var "aws_access_key=${{ secrets.AWS_ACCESS_KEY_ID }}" \
          -var "aws_secret_key=${{ secrets.AWS_SECRET_ACCESS_KEY }}" \
          -var "aws_session_token=${{ secrets.AWS_SESSION_TOKEN }}" \
          -var "nlb_dns=${NLB_DNS}"

