name: Terraform Cluster Deploy

on:
  workflow_run:
    workflows: ["Deploy Helm Chart to EKS"]
    types:
      - completed

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: us-east-1

      - name: Update kubeconfig
        run: |
          aws eks update-kubeconfig --region us-east-1 --name academy-eks-cluster

      - name: Install kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'latest'

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform Init
        working-directory: ./terraform/integration
        run: |
          export TF_LOG=DEBUG
          terraform init

      - name: Terraform Apply
        working-directory: ./terraform/integration
        run: |
          UM_NLB_ENDPOINT=$(kubectl get svc fiapx-user-management-svc -n default -o jsonpath='{.status.loadBalancer.ingress[0].hostname}')
          echo ${UM_NLB_ENDPOINT}
          UM_NLB_ARN_NUMBER=$(aws elbv2 describe-load-balancers --query "LoadBalancers[?DNSName=='${UM_NLB_ENDPOINT}'].[LoadBalancerArn]" --output text)
          echo ${UM_NLB_ARN_NUMBER}
          VP_NLB_ENDPOINT=$(kubectl get svc fiapx-video-processor-svc -n default -o jsonpath='{.status.loadBalancer.ingress[0].hostname}')
          echo ${VP_NLB_ENDPOINT}
          VP_NLB_ARN_NUMBER=$(aws elbv2 describe-load-balancers --query "LoadBalancers[?DNSName=='${VP_NLB_ENDPOINT}'].[LoadBalancerArn]" --output text)
          echo ${VP_NLB_ARN_NUMBER}
          terraform apply -auto-approve \
          -var "aws_region=us-east-1" \
          -var "aws_access_key=${{ secrets.AWS_ACCESS_KEY_ID }}" \
          -var "aws_secret_key=${{ secrets.AWS_SECRET_ACCESS_KEY }}" \
          -var "aws_session_token=${{ secrets.AWS_SESSION_TOKEN }}" \
          -var "user_management_nlb_dns=${UM_NLB_ENDPOINT}" \
          -var "user_management_nlb_arn=${UM_NLB_ARN_NUMBER}" \
          -var "video_processor_nlb_dns=${VP_NLB_ENDPOINT}" \
          -var "video_processor_nlb_arn=${VP_NLB_ARN_NUMBER}"

