name: Terraform Cluster Deploy

on:
  push:
    branches:
      - master
  repository_dispatch:
    types: [trigger-chart-deploy]

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: us-east-1

      - name: Create S3 bucket for Terraform state (Cluster)
        run: |
          aws s3api create-bucket \
            --bucket terraform-cluster-state-bucket \
            --region us-east-1

      - name: Create S3 bucket for Terraform state (Integration)
        run: |
          aws s3api create-bucket \
            --bucket terraform-integration-state-bucket \
            --region us-east-1

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform Init
        working-directory: ./terraform/cluster
        run: |
          export TF_LOG=DEBUG
          terraform init

      - name: Terraform Apply
        working-directory: ./terraform/cluster
        run: |
          terraform apply -auto-approve \
          -var "aws_region=us-east-1" \
          -var "aws_access_key=${{ secrets.AWS_ACCESS_KEY_ID }}" \
          -var "aws_secret_key=${{ secrets.AWS_SECRET_ACCESS_KEY }}" \
          -var "aws_session_token=${{ secrets.AWS_SESSION_TOKEN }}"

      - name: Install jq
        run: sudo apt-get update && sudo apt-get install -y jq

      - name: Export cluster outputs
        working-directory: ./terraform/cluster
        run: |
          export TF_LOG=ERROR
          terraform output -json | jq 'map_values(.value)' > ../integration/raw_cluster_outputs.json

      - name: Clean JSON with jq
        working-directory: ./terraform/cluster
        run: jq 'map_values(.value)' ../integration/raw_cluster_outputs.json > ../integration/cluster_outputs.json

      - name: Upload Output
        working-directory: ./terraform/cluster
        run: |
          aws s3 cp ../integration/cluster_outputs.json s3://terraform-integration-state-bucket/cluster_outputs.json

